### ISSUE TITLE
Extension Documentation Template

### ISSUE THREAD

**Issue by daniellacor** [ceros/ceros-labs#5]
Review URL Scroll to Anchor doc to be used as client-facing template moving forward.

https://docs.google.com/document/d/11wpEao_0ISKmVpXAaNz6kCKla7-Sb1MRbpJxDeJZw3c/edit?usp=sharing

**Comment by tommydarko** [comment]
@daniellacor finished the review and left two small comments about the anchor functionality, but in terms of the template format itself: :+1:
